Configuracion Inicial

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import re
from datetime import datetime

In [2]:
import pandas as pd

ruta = r"C:\Users\Vìctor\OneDrive\Desktop\ESP_Project\Datos\DATOS_ESP.xlsx"

# Cargar solo la hoja que te interesa
df = pd.read_excel(ruta, sheet_name="SCHAO-473HS1UI")

# Mostrar todas las columnas tal como están escritas
print("Columnas del archivo:")
print(df.columns.tolist())

Columnas del archivo:
['    @Name( )  ', '      Date ', 'PRUEBA DE PRODUCCION PETRÓLEO A 24 HORAS bbl/d ', 'PRUEBA DE PRODUCCIÓN AGUA A 24 HORAS bbl/d ', '    Prueba_pozo.Oil_24 + Prueba_pozo.Water_24  ', 'PRUEBA DE PRODUCCIÓN GAS A 24 HORAS Mcf/d ', '  BSW   % ', 'GRAVEDAD API DEL PETROLEO  ', 'SALINIDAD   PPM PU ', 'PRESION DE INTAKE psi ', 'FRECUENCIA BOMBA Hz  ', 'AMPERAJE BOMBA Amp  ', 'PRESION DE TUBING psi ', 'PRESION DE CASING psi ', 'TIPO DE BOMBA  ', 'TEMPERATURA DE LA BOMBA Deg. F ', 'ETAPAS DE LA BOMBA  ', 'CAMPO']

In [3]:
import pandas as pd

# Ruta al archivo limpio anterior
ruta = r"C:\Users\Vìctor\OneDrive\Desktop\ESP_Project\Datos\DATOS_ESP.xlsx"

# 1. Cargar hoja específica
df = pd.read_excel(ruta, sheet_name="SCHAO-473HS1UI")

# 2. Limpiar columnas
df.columns = (
    df.columns
    .str.strip()
    .str.upper()
    .str.replace(" +", " ", regex=True)
)

# 3. Detectar si la columna DATE está en formato numérico
df["DATE_ORIGINAL"] = df["DATE"]  # copia para revisar después

# Intentar convertir fechas: si es número, transformar como serial Excel
def convertir_fecha(x):
    try:
        if isinstance(x, (int, float)):
            return pd.to_datetime("1899-12-30") + pd.to_timedelta(x, unit="D")
        return pd.to_datetime(x, dayfirst=True, errors="coerce")
    except:
        return pd.NaT

df["DATE"] = df["DATE_ORIGINAL"].apply(convertir_fecha)

# 4. Mostrar cuántas fechas no se pudieron convertir
print("❗ Fechas inválidas:", df["DATE"].isna().sum())

# 5. Ordenar
df = df.sort_values("DATE").reset_index(drop=True)

# 6. Guardar limpio
df.to_excel("df_SCHAO473HS1UI_fechas_corregidas.xlsx", index=False)

# 7. Verificar visualmente
print(df[["DATE_ORIGINAL", "DATE"]].head(10))

C:\Users\Vìctor\AppData\Local\Temp\ipykernel_19240\100750461.py:25: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(x, dayfirst=True, errors="coerce")

❗ Fechas inválidas: 0
         DATE_ORIGINAL       DATE
0  2015-01-07 00:00:00 2015-01-07
1  2015-01-08 00:00:00 2015-01-08
2  2015-02-01 00:00:00 2015-02-01
3  2015-02-12 00:00:00 2015-02-12
4            2/18/2015 2015-02-18
5            2/23/2015 2015-02-23
6            2/25/2015 2015-02-25
7  2015-04-07 00:00:00 2015-04-07
8            4/15/2015 2015-04-15
9            4/21/2015 2015-04-21

In [4]:
df.head(30)

,@NAME( ),DATE,PRUEBA DE PRODUCCION PETRÓLEO A 24 HORAS BBL/D,PRUEBA DE PRODUCCIÓN AGUA A 24 HORAS BBL/D,PRUEBA_POZO.OIL_24 + PRUEBA_POZO.WATER_24,PRUEBA DE PRODUCCIÓN GAS A 24 HORAS MCF/D,BSW %,GRAVEDAD API DEL PETROLEO,SALINIDAD PPM PU,PRESION DE INTAKE PSI,FRECUENCIA BOMBA HZ,AMPERAJE BOMBA AMP,PRESION DE TUBING PSI,PRESION DE CASING PSI,TIPO DE BOMBA,TEMPERATURA DE LA BOMBA DEG. F,ETAPAS DE LA BOMBA,CAMPO,DATE_ORIGINAL
0,SCHAO-473HS1UI,2015-01-07,1488.0,470.0,1958.0,0.00,24.00,18.2,NaN,NaN,NaN,NaN,120.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-01-07 00:00:00
1,SCHAO-473HS1UI,2015-01-08,1357.0,528.0,1885.0,0.00,28.01,18.2,NaN,NaN,NaN,NaN,110.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-01-08 00:00:00
2,SCHAO-473HS1UI,2015-02-01,1436.0,359.0,1795.0,0.00,20.00,18.2,NaN,NaN,NaN,NaN,170.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-02-01 00:00:00
3,SCHAO-473HS1UI,2015-02-12,1159.0,597.0,1756.0,0.00,34.00,18.2,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-02-12 00:00:00
4,SCHAO-473HS1UI,2015-02-18,1714.0,429.0,2143.0,0.00,20.02,18.2,NaN,NaN,NaN,NaN,150.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2/18/2015
5,SCHAO-473HS1UI,2015-02-23,1737.0,434.0,2171.0,0.00,19.99,18.2,NaN,NaN,NaN,NaN,140.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2/23/2015
6,SCHAO-473HS1UI,2015-02-25,1650.0,521.0,2171.0,0.00,24.00,18.2,NaN,NaN,NaN,NaN,140.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2/25/2015
7,SCHAO-473HS1UI,2015-04-07,1410.0,548.0,1958.0,0.00,27.99,18.2,NaN,NaN,NaN,NaN,120.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-04-07 00:00:00
8,SCHAO-473HS1UI,2015-04-15,1525.0,481.0,2006.0,0.00,23.98,18.2,NaN,NaN,NaN,NaN,130.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,4/15/2015
9,SCHAO-473HS1UI,2015-04-21,1547.0,489.0,2036.0,0.00,24.02,18.2,NaN,NaN,NaN,NaN,125.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,4/21/2015
10,SCHAO-473HS1UI,2015-04-27,1547.0,489.0,2036.0,0.00,24.02,18.2,NaN,NaN,NaN,NaN,125.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,4/27/2015
11,SCHAO-473HS1UI,2015-05-05,1531.0,483.0,2014.0,0.00,23.98,18.2,NaN,NaN,NaN,NaN,125.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-05-05 00:00:00
12,SCHAO-473HS1UI,2015-06-04,1556.0,492.0,2048.0,0.00,24.02,18.2,NaN,NaN,NaN,NaN,130.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-06-04 00:00:00
13,SCHAO-473HS1UI,2015-06-30,1488.0,470.0,1958.0,0.00,24.00,18.2,NaN,NaN,NaN,NaN,110.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,6/30/2015
14,SCHAO-473HS1UI,2015-07-15,1402.0,545.0,1947.0,0.00,27.99,18.2,NaN,NaN,NaN,NaN,110.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,7/15/2015
15,SCHAO-473HS1UI,2015-08-09,1395.0,543.0,1938.0,0.00,28.02,18.2,NaN,NaN,NaN,NaN,105.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-08-09 00:00:00
16,SCHAO-473HS1UI,2015-09-18,1279.0,659.0,1938.0,0.00,34.00,18.2,NaN,NaN,NaN,NaN,105.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,9/18/2015
17,SCHAO-473HS1UI,2015-10-01,1544.0,386.0,1930.0,0.00,20.00,18.2,NaN,NaN,NaN,NaN,170.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-10-01 00:00:00
18,SCHAO-473HS1UI,2015-11-26,1152.0,593.0,1745.0,0.00,33.98,18.2,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,11/26/2015
19,SCHAO-473HS1UI,2015-12-10,1200.0,618.0,1818.0,0.00,33.99,18.2,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-12-10 00:00:00
20,SCHAO-473HS1UI,2015-12-11,1137.0,585.0,1722.0,0.00,33.97,18.2,NaN,NaN,NaN,NaN,80.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-12-11 00:00:00
21,SCHAO-473HS1UI,2015-12-18,1159.0,597.0,1756.0,0.00,34.00,18.2,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,12/18/2015
22,SCHAO-473HS1UI,2015-12-24,1129.0,582.0,1711.0,0.00,34.01,18.2,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,12/24/2015
23,SCHAO-473HS1UI,2015-12-25,1061.0,650.0,1711.0,0.00,37.99,18.2,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,12/25/2015
24,SCHAO-473HS1UI,2016-01-08,1110.0,872.0,1982.0,172.05,44.00,18.2,NaN,NaN,NaN,NaN,90.0,NaN,SN3600,NaN,NaN,SACHA NORTE 1,2016-01-08 00:00:00
25,SCHAO-473HS1UI,2016-01-20,1068.0,654.0,1722.0,0.00,37.98,18.2,NaN,NaN,NaN,NaN,80.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,1/20/2016
26,SCHAO-473HS1UI,2016-01-27,1061.0,650.0,1711.0,0.00,37.99,18.2,NaN,NaN,NaN,NaN,75.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,1/27/2016
27,SCHAO-473HS1UI,2016-02-06,1030.0,810.0,1840.0,0.00,44.02,18.2,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2016-02-06 00:00:00
28,SCHAO-473HS1UI,2016-02-08,1031.0,951.0,1982.0,159.81,47.98,18.2,NaN,NaN,NaN,NaN,90.0,NaN,SN3600,NaN,NaN,SACHA NORTE 1,2016-02-08 00:00:00
29,SCHAO-473HS1UI,2016-02-20,1022.0,627.0,1649.0,0.00,38.02,18.2,NaN,NaN,NaN,NaN,80.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,2/20/2016

In [5]:
df_verificado = pd.read_excel("df_SCHAO473HS1UI_fechas_corregidas.xlsx")
df_verificado.head(30)

,@NAME( ),DATE,PRUEBA DE PRODUCCION PETRÓLEO A 24 HORAS BBL/D,PRUEBA DE PRODUCCIÓN AGUA A 24 HORAS BBL/D,PRUEBA_POZO.OIL_24 + PRUEBA_POZO.WATER_24,PRUEBA DE PRODUCCIÓN GAS A 24 HORAS MCF/D,BSW %,GRAVEDAD API DEL PETROLEO,SALINIDAD PPM PU,PRESION DE INTAKE PSI,FRECUENCIA BOMBA HZ,AMPERAJE BOMBA AMP,PRESION DE TUBING PSI,PRESION DE CASING PSI,TIPO DE BOMBA,TEMPERATURA DE LA BOMBA DEG. F,ETAPAS DE LA BOMBA,CAMPO,DATE_ORIGINAL
0,SCHAO-473HS1UI,2015-01-07,1488,470,1958,0.00,24.00,18.2,NaN,NaN,NaN,NaN,120,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-01-07 00:00:00
1,SCHAO-473HS1UI,2015-01-08,1357,528,1885,0.00,28.01,18.2,NaN,NaN,NaN,NaN,110,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-01-08 00:00:00
2,SCHAO-473HS1UI,2015-02-01,1436,359,1795,0.00,20.00,18.2,NaN,NaN,NaN,NaN,170,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-02-01 00:00:00
3,SCHAO-473HS1UI,2015-02-12,1159,597,1756,0.00,34.00,18.2,NaN,NaN,NaN,NaN,90,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-02-12 00:00:00
4,SCHAO-473HS1UI,2015-02-18,1714,429,2143,0.00,20.02,18.2,NaN,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,SACHA NORTE 1,2/18/2015
5,SCHAO-473HS1UI,2015-02-23,1737,434,2171,0.00,19.99,18.2,NaN,NaN,NaN,NaN,140,NaN,NaN,NaN,NaN,SACHA NORTE 1,2/23/2015
6,SCHAO-473HS1UI,2015-02-25,1650,521,2171,0.00,24.00,18.2,NaN,NaN,NaN,NaN,140,NaN,NaN,NaN,NaN,SACHA NORTE 1,2/25/2015
7,SCHAO-473HS1UI,2015-04-07,1410,548,1958,0.00,27.99,18.2,NaN,NaN,NaN,NaN,120,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-04-07 00:00:00
8,SCHAO-473HS1UI,2015-04-15,1525,481,2006,0.00,23.98,18.2,NaN,NaN,NaN,NaN,130,NaN,NaN,NaN,NaN,SACHA NORTE 1,4/15/2015
9,SCHAO-473HS1UI,2015-04-21,1547,489,2036,0.00,24.02,18.2,NaN,NaN,NaN,NaN,125,NaN,NaN,NaN,NaN,SACHA NORTE 1,4/21/2015
10,SCHAO-473HS1UI,2015-04-27,1547,489,2036,0.00,24.02,18.2,NaN,NaN,NaN,NaN,125,NaN,NaN,NaN,NaN,SACHA NORTE 1,4/27/2015
11,SCHAO-473HS1UI,2015-05-05,1531,483,2014,0.00,23.98,18.2,NaN,NaN,NaN,NaN,125,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-05-05 00:00:00
12,SCHAO-473HS1UI,2015-06-04,1556,492,2048,0.00,24.02,18.2,NaN,NaN,NaN,NaN,130,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-06-04 00:00:00
13,SCHAO-473HS1UI,2015-06-30,1488,470,1958,0.00,24.00,18.2,NaN,NaN,NaN,NaN,110,NaN,NaN,NaN,NaN,SACHA NORTE 1,6/30/2015
14,SCHAO-473HS1UI,2015-07-15,1402,545,1947,0.00,27.99,18.2,NaN,NaN,NaN,NaN,110,NaN,NaN,NaN,NaN,SACHA NORTE 1,7/15/2015
15,SCHAO-473HS1UI,2015-08-09,1395,543,1938,0.00,28.02,18.2,NaN,NaN,NaN,NaN,105,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-08-09 00:00:00
16,SCHAO-473HS1UI,2015-09-18,1279,659,1938,0.00,34.00,18.2,NaN,NaN,NaN,NaN,105,NaN,NaN,NaN,NaN,SACHA NORTE 1,9/18/2015
17,SCHAO-473HS1UI,2015-10-01,1544,386,1930,0.00,20.00,18.2,NaN,NaN,NaN,NaN,170,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-10-01 00:00:00
18,SCHAO-473HS1UI,2015-11-26,1152,593,1745,0.00,33.98,18.2,NaN,NaN,NaN,NaN,90,NaN,NaN,NaN,NaN,SACHA NORTE 1,11/26/2015
19,SCHAO-473HS1UI,2015-12-10,1200,618,1818,0.00,33.99,18.2,NaN,NaN,NaN,NaN,100,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-12-10 00:00:00
20,SCHAO-473HS1UI,2015-12-11,1137,585,1722,0.00,33.97,18.2,NaN,NaN,NaN,NaN,80,NaN,NaN,NaN,NaN,SACHA NORTE 1,2015-12-11 00:00:00
21,SCHAO-473HS1UI,2015-12-18,1159,597,1756,0.00,34.00,18.2,NaN,NaN,NaN,NaN,90,NaN,NaN,NaN,NaN,SACHA NORTE 1,12/18/2015
22,SCHAO-473HS1UI,2015-12-24,1129,582,1711,0.00,34.01,18.2,NaN,NaN,NaN,NaN,90,NaN,NaN,NaN,NaN,SACHA NORTE 1,12/24/2015
23,SCHAO-473HS1UI,2015-12-25,1061,650,1711,0.00,37.99,18.2,NaN,NaN,NaN,NaN,90,NaN,NaN,NaN,NaN,SACHA NORTE 1,12/25/2015
24,SCHAO-473HS1UI,2016-01-08,1110,872,1982,172.05,44.00,18.2,NaN,NaN,NaN,NaN,90,NaN,SN3600,NaN,NaN,SACHA NORTE 1,2016-01-08 00:00:00
25,SCHAO-473HS1UI,2016-01-20,1068,654,1722,0.00,37.98,18.2,NaN,NaN,NaN,NaN,80,NaN,NaN,NaN,NaN,SACHA NORTE 1,1/20/2016
26,SCHAO-473HS1UI,2016-01-27,1061,650,1711,0.00,37.99,18.2,NaN,NaN,NaN,NaN,75,NaN,NaN,NaN,NaN,SACHA NORTE 1,1/27/2016
27,SCHAO-473HS1UI,2016-02-06,1030,810,1840,0.00,44.02,18.2,NaN,NaN,NaN,NaN,90,NaN,NaN,NaN,NaN,SACHA NORTE 1,2016-02-06 00:00:00
28,SCHAO-473HS1UI,2016-02-08,1031,951,1982,159.81,47.98,18.2,NaN,NaN,NaN,NaN,90,NaN,SN3600,NaN,NaN,SACHA NORTE 1,2016-02-08 00:00:00
29,SCHAO-473HS1UI,2016-02-20,1022,627,1649,0.00,38.02,18.2,NaN,NaN,NaN,NaN,80,NaN,NaN,NaN,NaN,SACHA NORTE 1,2/20/2016