EXPLORACION df_total_pozos_limpio.ipynb

Importacion de librerias

In [ ]:
# --- 1. Librerías necesarias ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 2. Cargar el archivo Excel ---
ruta = r'C:\Users\Vìctor\OneDrive\Desktop\ESP_Project\df_total_pozos_limpio.xlsx'
df = pd.read_excel(ruta)

# --- 3. Mostrar las primeras filas y dimensiones ---
print("Dimensiones:", df.shape)
df.head()

Dimensiones: (16161, 38)

,@NAME( ),DATE,PRUEBA DE PRODUCCION PETRÓLEO A 24 HORAS BBL/D,PRUEBA DE PRODUCCIÓN AGUA A 24 HORAS BBL/D,PRUEBA_POZO.OIL_24 + PRUEBA_POZO.WATER_24,PRUEBA DE PRODUCCIÓN GAS A 24 HORAS MCF/D,BSW %,GRAVEDAD API DEL PETROLEO,SALINIDAD PPM PU,PRESION DE INTAKE PSI,...,UNNAMED: 9,UNNAMED: 10,UNNAMED: 11,UNNAMED: 12,UNNAMED: 13,UNNAMED: 14,UNNAMED: 15,UNNAMED: 16,UNNAMED: 17,UNNAMED: 18
0,SCHAO-473HS1UI,2015-01-07,1488.0,470.0,1958.0,0.0,24.00,18.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SCHAO-473HS1UI,2015-01-08,1357.0,528.0,1885.0,0.0,28.01,18.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SCHAO-473HS1UI,2015-02-01,1436.0,359.0,1795.0,0.0,20.00,18.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SCHAO-473HS1UI,2015-02-12,1159.0,597.0,1756.0,0.0,34.00,18.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SCHAO-473HS1UI,2015-02-18,1714.0,429.0,2143.0,0.0,20.02,18.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.tail(20)

,@NAME( ),DATE,PRUEBA DE PRODUCCION PETRÓLEO A 24 HORAS BBL/D,PRUEBA DE PRODUCCIÓN AGUA A 24 HORAS BBL/D,PRUEBA_POZO.OIL_24 + PRUEBA_POZO.WATER_24,PRUEBA DE PRODUCCIÓN GAS A 24 HORAS MCF/D,BSW %,GRAVEDAD API DEL PETROLEO,SALINIDAD PPM PU,PRESION DE INTAKE PSI,...,UNNAMED: 9,UNNAMED: 10,UNNAMED: 11,UNNAMED: 12,UNNAMED: 13,UNNAMED: 14,UNNAMED: 15,UNNAMED: 16,UNNAMED: 17,UNNAMED: 18
16141,SCHAJ-428TI,2025-05-05,61.0,449.0,510.0,17.69,88.04,28.5,41000.0,424.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16142,SCHAJ-428TI,2025-05-22,109.0,436.0,545.0,31.50,80.00,28.5,41000.0,418.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16143,SCHAJ-428TI,2025-05-28,109.0,436.0,545.0,31.50,80.00,28.5,48600.0,418.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16144,SCHAJ-428TI,2025-06-16,109.0,436.0,545.0,31.50,80.00,28.5,48600.0,379.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16145,SCHAJ-428TI,2025-06-18,127.0,507.0,634.0,36.70,79.97,28.5,48600.0,366.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16146,SCHAJ-428TI,2025-08-05,66.0,488.0,554.0,19.07,88.09,28.5,41000.0,417.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16147,SCHAJ-428TI,2025-08-18,56.0,504.0,560.0,16.18,90.00,28.5,17.2,445.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16148,SCHAJ-428TI,2025-08-19,69.0,618.0,687.0,19.94,89.96,28.5,17.2,407.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16149,SCHAJ-428TI,2025-08-20,86.0,632.0,718.0,20.81,88.02,28.5,17.2,392.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16150,SCHAJ-428TI,2025-08-21,154.0,704.0,858.0,29.77,82.05,28.5,44000.0,317.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16151,SCHAJ-428TI,2025-08-23,158.0,832.0,990.0,45.94,84.04,28.5,44800.0,345.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16152,SCHAJ-428TI,2025-08-25,151.0,856.0,1007.0,43.80,85.00,28.5,44800.0,339.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16153,SCHAJ-428TI,2025-09-01,48.0,44.0,92.0,38.00,47.83,28.5,41000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16154,SCHAJ-428TI,2025-09-03,48.0,44.0,92.0,38.00,47.83,28.5,41000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16155,SCHAJ-428TI,2025-09-05,109.0,436.0,545.0,31.50,80.00,28.5,41000.0,418.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16156,SCHAJ-428TI,2025-09-18,209.0,834.0,1043.0,60.40,79.96,28.5,44800.0,310.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16157,SCHAJ-428TI,2025-09-20,205.0,822.0,1027.0,59.25,80.04,28.5,44800.0,308.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16158,SCHAJ-428TI,2025-10-22,208.0,830.0,1038.0,59.25,79.96,28.5,44800.0,300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16159,SCHAJ-428TI,2025-11-02,48.0,44.0,92.0,38.00,47.83,28.5,41000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16160,SCHAJ-428TI,2025-11-09,208.0,831.0,1039.0,60.26,79.98,28.5,44800.0,323.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Validar las columnas y tipos de datos

In [3]:
# Ver columnas y tipos
df.info()

# Comprobar si alguna columna contiene "fecha"
fechas = [col for col in df.columns if 'fecha' in col.lower()]
print("Columnas que contienen fechas:", fechas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16161 entries, 0 to 16160
Data columns (total 38 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   @NAME( )                                        16161 non-null  object
 1   DATE                                            16161 non-null  datetime64[ns]
 2   PRUEBA DE PRODUCCION PETRÓLEO A 24 HORAS BBL/D  16161 non-null  float64
 3   PRUEBA DE PRODUCCIÓN AGUA A 24 HORAS BBL/D      16161 non-null  float64
 4   PRUEBA_POZO.OIL_24 + PRUEBA_POZO.WATER_24       16161 non-null  float64
 5   PRUEBA DE PRODUCCIÓN GAS A 24 HORAS MCF/D       16161 non-null  float64
 6   BSW %                                           16156 non-null  float64
 7   GRAVEDAD API DEL PETROLEO                       16096 non-null  float64
 8   SALINIDAD PPM PU                                13820 non-null  float64
 9   PRESION DE INTAKE PSI                           10948 non-null  float64
 10  FRECUENCIA BOMBA HZ                             13388 non-null  float64
 11  AMPERAJE BOMBA AMP                              13272 non-null  float64
 12  PRESION DE TUBING PSI                           16123 non-null  float64
 13  PRESION DE CASING PSI                           5150 non-null   float64
 14  TIPO DE BOMBA                                   14365 non-null  object
 15  TEMPERATURA DE LA BOMBA DEG. F                  9576 non-null   float64
 16  ETAPAS DE LA BOMBA                              14140 non-null  float64
 17  CAMPO                                           8873 non-null   object
 18  POZO                                            16161 non-null  object
 19  FECHA:                                          0 non-null      float64
 20  Unnamed: 20                                     0 non-null      float64
 21  UNNAMED: 2                                      0 non-null      float64
 22  UNNAMED: 3                                      0 non-null      float64
 23  UNNAMED: 4                                      0 non-null      float64
 24  UNNAMED: 5                                      0 non-null      float64
 25  UNNAMED: 6                                      0 non-null      float64
 26  UNNAMED: 7                                      0 non-null      float64
 27  UNNAMED: 8                                      0 non-null      float64
 28  UNNAMED: 9                                      0 non-null      float64
 29  UNNAMED: 10                                     0 non-null      float64
 30  UNNAMED: 11                                     0 non-null      float64
 31  UNNAMED: 12                                     0 non-null      float64
 32  UNNAMED: 13                                     0 non-null      float64
 33  UNNAMED: 14                                     0 non-null      float64
 34  UNNAMED: 15                                     0 non-null      float64
 35  UNNAMED: 16                                     0 non-null      float64
 36  UNNAMED: 17                                     0 non-null      float64
 37  UNNAMED: 18                                     0 non-null      float64
dtypes: datetime64[ns](1), float64(33), object(4)
memory usage: 4.7+ MB
Columnas que contienen fechas: ['FECHA:']

Procesar y validar fechas

In [4]:
# Supongamos que la columna se llama 'Fecha'
col_fecha = fechas[0]  # si solo hay una
df[col_fecha] = pd.to_datetime(df[col_fecha], errors='coerce')

# Rango de fechas
print("Fecha mínima:", df[col_fecha].min())
print("Fecha máxima:", df[col_fecha].max())

Fecha mínima: NaT
Fecha máxima: NaT

Verificar nulos y duplicados

In [5]:
# Nulos por columna
df.isnull().sum()

# Duplicados por fecha (si aplica)
duplicados_fecha = df.duplicated(subset=[col_fecha])
print(f"Duplicados por fecha: {duplicados_fecha.sum()} registros")

Duplicados por fecha: 16160 registros

In [2]:
# Copia de seguridad del DataFrame
df_raw = df.copy()

# 1. Renombrar columnas automáticamente (sin tildes, espacios, símbolos raros)
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=False)
    .str.replace('%', 'pct', regex=False)
    .str.replace(r'[^\w\s]', '', regex=True)  # Elimina símbolos como ":"
)

# 2. Mostrar nombres resultantes
print("Columnas limpias:")
print(df.columns.tolist())

Columnas limpias:
['name_', 'date', 'prueba_de_produccion_petróleo_a_24_horas_bbld', 'prueba_de_producción_agua_a_24_horas_bbld', 'prueba_pozooil_24__prueba_pozowater_24', 'prueba_de_producción_gas_a_24_horas_mcfd', 'bsw_pct', 'gravedad_api_del_petroleo', 'salinidad_ppm_pu', 'presion_de_intake_psi', 'frecuencia_bomba_hz', 'amperaje_bomba_amp', 'presion_de_tubing_psi', 'presion_de_casing_psi', 'tipo_de_bomba', 'temperatura_de_la_bomba_deg_f', 'etapas_de_la_bomba', 'campo', 'pozo', 'fecha', 'unnamed_20', 'unnamed_2', 'unnamed_3', 'unnamed_4', 'unnamed_5', 'unnamed_6', 'unnamed_7', 'unnamed_8', 'unnamed_9', 'unnamed_10', 'unnamed_11', 'unnamed_12', 'unnamed_13', 'unnamed_14', 'unnamed_15', 'unnamed_16', 'unnamed_17', 'unnamed_18']

In [3]:
# Verificar cuántos valores no nulos hay por columna unnamed
unnamed_cols = [col for col in df.columns if 'unnamed' in col]
df[unnamed_cols].notna().sum()

unnamed_20    0
unnamed_2     0
unnamed_3     0
unnamed_4     0
unnamed_5     0
unnamed_6     0
unnamed_7     0
unnamed_8     0
unnamed_9     0
unnamed_10    0
unnamed_11    0
unnamed_12    0
unnamed_13    0
unnamed_14    0
unnamed_15    0
unnamed_16    0
unnamed_17    0
unnamed_18    0
dtype: int64

In [4]:
df = df.drop(columns=[col for col in df.columns if 'unnamed' in col])

Verificar tipos de datos y valores nulos

In [5]:
# Tipos de datos y resumen de valores nulos
df.info()

# Porcentaje de nulos por columna
(df.isnull().mean() * 100).round(2).sort_values(ascending=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16161 entries, 0 to 16160
Data columns (total 20 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   name_                                          16161 non-null  object
 1   date                                           16161 non-null  datetime64[ns]
 2   prueba_de_produccion_petróleo_a_24_horas_bbld  16161 non-null  float64
 3   prueba_de_producción_agua_a_24_horas_bbld      16161 non-null  float64
 4   prueba_pozooil_24__prueba_pozowater_24         16161 non-null  float64
 5   prueba_de_producción_gas_a_24_horas_mcfd       16161 non-null  float64
 6   bsw_pct                                        16156 non-null  float64
 7   gravedad_api_del_petroleo                      16096 non-null  float64
 8   salinidad_ppm_pu                               13820 non-null  float64
 9   presion_de_intake_psi                          10948 non-null  float64
 10  frecuencia_bomba_hz                            13388 non-null  float64
 11  amperaje_bomba_amp                             13272 non-null  float64
 12  presion_de_tubing_psi                          16123 non-null  float64
 13  presion_de_casing_psi                          5150 non-null   float64
 14  tipo_de_bomba                                  14365 non-null  object
 15  temperatura_de_la_bomba_deg_f                  9576 non-null   float64
 16  etapas_de_la_bomba                             14140 non-null  float64
 17  campo                                          8873 non-null   object
 18  pozo                                           16161 non-null  object
 19  fecha                                          0 non-null      float64
dtypes: datetime64[ns](1), float64(15), object(4)
memory usage: 2.5+ MB

fecha                                            100.00
presion_de_casing_psi                             68.13
campo                                             45.10
temperatura_de_la_bomba_deg_f                     40.75
presion_de_intake_psi                             32.26
amperaje_bomba_amp                                17.88
frecuencia_bomba_hz                               17.16
salinidad_ppm_pu                                  14.49
etapas_de_la_bomba                                12.51
tipo_de_bomba                                     11.11
gravedad_api_del_petroleo                          0.40
presion_de_tubing_psi                              0.24
bsw_pct                                            0.03
prueba_de_produccion_petróleo_a_24_horas_bbld      0.00
date                                               0.00
name_                                              0.00
prueba_de_producción_agua_a_24_horas_bbld          0.00
prueba_pozooil_24__prueba_pozowater_24             0.00
prueba_de_producción_gas_a_24_horas_mcfd           0.00
pozo                                               0.00
dtype: float64

In [6]:
df.head()

,name_,date,prueba_de_produccion_petróleo_a_24_horas_bbld,prueba_de_producción_agua_a_24_horas_bbld,prueba_pozooil_24__prueba_pozowater_24,prueba_de_producción_gas_a_24_horas_mcfd,bsw_pct,gravedad_api_del_petroleo,salinidad_ppm_pu,presion_de_intake_psi,frecuencia_bomba_hz,amperaje_bomba_amp,presion_de_tubing_psi,presion_de_casing_psi,tipo_de_bomba,temperatura_de_la_bomba_deg_f,etapas_de_la_bomba,campo,pozo,fecha
0,SCHAO-473HS1UI,2015-01-07,1488.0,470.0,1958.0,0.0,24.00,18.2,NaN,NaN,NaN,NaN,120.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,SCHAO-473HS1UI,NaN
1,SCHAO-473HS1UI,2015-01-08,1357.0,528.0,1885.0,0.0,28.01,18.2,NaN,NaN,NaN,NaN,110.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,SCHAO-473HS1UI,NaN
2,SCHAO-473HS1UI,2015-02-01,1436.0,359.0,1795.0,0.0,20.00,18.2,NaN,NaN,NaN,NaN,170.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,SCHAO-473HS1UI,NaN
3,SCHAO-473HS1UI,2015-02-12,1159.0,597.0,1756.0,0.0,34.00,18.2,NaN,NaN,NaN,NaN,90.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,SCHAO-473HS1UI,NaN
4,SCHAO-473HS1UI,2015-02-18,1714.0,429.0,2143.0,0.0,20.02,18.2,NaN,NaN,NaN,NaN,150.0,NaN,NaN,NaN,NaN,SACHA NORTE 1,SCHAO-473HS1UI,NaN

In [7]:
df.tail(10)

,name_,date,prueba_de_produccion_petróleo_a_24_horas_bbld,prueba_de_producción_agua_a_24_horas_bbld,prueba_pozooil_24__prueba_pozowater_24,prueba_de_producción_gas_a_24_horas_mcfd,bsw_pct,gravedad_api_del_petroleo,salinidad_ppm_pu,presion_de_intake_psi,frecuencia_bomba_hz,amperaje_bomba_amp,presion_de_tubing_psi,presion_de_casing_psi,tipo_de_bomba,temperatura_de_la_bomba_deg_f,etapas_de_la_bomba,campo,pozo,fecha
16151,SCHAJ-428TI,2025-08-23,158.0,832.0,990.0,45.94,84.04,28.5,44800.0,345.0,54.0,33.0,240.0,50.0,SF-900|SF-900|SF-900|SF-900,268.0,492.0,NaN,SCHAJ-428TI,NaN
16152,SCHAJ-428TI,2025-08-25,151.0,856.0,1007.0,43.80,85.00,28.5,44800.0,339.0,54.0,34.0,300.0,50.0,SF-900|SF-900|SF-900|SF-900,267.0,492.0,NaN,SCHAJ-428TI,NaN
16153,SCHAJ-428TI,2025-09-01,48.0,44.0,92.0,38.00,47.83,28.5,41000.0,NaN,60.0,NaN,150.0,150.0,RCXLF|RCXLF|RCXLF|RCXLF,NaN,359.0,NaN,SCHAJ-428TI,NaN
16154,SCHAJ-428TI,2025-09-03,48.0,44.0,92.0,38.00,47.83,28.5,41000.0,NaN,60.0,NaN,150.0,150.0,RCXLF|RCXLF|RCXLF|RCXLF,NaN,359.0,NaN,SCHAJ-428TI,NaN
16155,SCHAJ-428TI,2025-09-05,109.0,436.0,545.0,31.50,80.00,28.5,41000.0,418.0,65.0,33.0,170.0,150.0,RCXLF|RCXLF|RCXLF|RCXLF,291.0,359.0,NaN,SCHAJ-428TI,NaN
16156,SCHAJ-428TI,2025-09-18,209.0,834.0,1043.0,60.40,79.96,28.5,44800.0,310.0,56.0,36.0,260.0,50.0,SF-900|SF-900|SF-900|SF-900,274.0,492.0,NaN,SCHAJ-428TI,NaN
16157,SCHAJ-428TI,2025-09-20,205.0,822.0,1027.0,59.25,80.04,28.5,44800.0,308.0,56.0,36.0,300.0,50.0,SF-900|SF-900|SF-900|SF-900,275.0,492.0,NaN,SCHAJ-428TI,NaN
16158,SCHAJ-428TI,2025-10-22,208.0,830.0,1038.0,59.25,79.96,28.5,44800.0,300.0,57.0,37.0,300.0,50.0,SF-900|SF-900|SF-900|SF-900,279.0,492.0,NaN,SCHAJ-428TI,NaN
16159,SCHAJ-428TI,2025-11-02,48.0,44.0,92.0,38.00,47.83,28.5,41000.0,NaN,60.0,NaN,150.0,150.0,RCXLF|RCXLF|RCXLF|RCXLF,NaN,359.0,NaN,SCHAJ-428TI,NaN
16160,SCHAJ-428TI,2025-11-09,208.0,831.0,1039.0,60.26,79.98,28.5,44800.0,323.0,55.0,34.0,240.0,50.0,SF-900|SF-900|SF-900|SF-900,280.0,492.0,NaN,SCHAJ-428TI,NaN

Código completo para merge

In [11]:
import pandas as pd

# 1. Cargar el dataset principal (si no lo tienes ya cargado)
# df = pd.read_excel("ruta_a_df_total_pozos_limpio.xlsx")  # si aplica

# 2. Cargar el archivo con mapeo POZO → CAMPO
ruta_campos = r'C:\Users\Vìctor\OneDrive\Desktop\ESP_Project\Datos\CampoSachamMejoresPozos.xlsx'
df_campo = pd.read_excel(ruta_campos, usecols=['POZO', 'CAMPO'])

# 3. Asegurarse que no haya duplicados (ya lo confirmamos)
df_mapeo = df_campo.drop_duplicates().copy()
df_mapeo.columns = ['pozo', 'campo_referencia']  # normalizar nombres

# 4. Merge solo por 'pozo'
df = df.merge(df_mapeo, on='pozo', how='left')

# 5. Rellenar campo si está vacío (NaN)
df['campo'] = df['campo'].fillna(df['campo_referencia'])

# 6. Eliminar columna auxiliar
df.drop(columns='campo_referencia', inplace=True)

# 7. Ver cuántos se llenaron
completados = df['campo'].notna().sum()
print(f"✅ Campo completado en {completados} registros de {len(df)}")

✅ Campo completado en 16161 registros de 16161

Convertir a EXCEL el dataset relizado merge

In [12]:
df.to_excel(r'C:\Users\Vìctor\OneDrive\Desktop\ESP_Project\df_completo_con_campo.xlsx', index=False)